config/routes.rb
Rails.application.routes.draw do

  resources :printers

  resources :barcodes do
    get :scan, on: :collection
    get :unlink_pallet, on: :member
    get :in, on: :collection
    get :in_scan, on: :collection
    post :in_putaway, on: :collection
    get :repeat_printer, on: :collection
    get :printer_label, on: :collection
  end

  resources :stock_masters
  resources :stock_trans do
    get :in, :on => :collection
    get :in_scan, :on => :collection
    get :out, :on => :collection
  end

  resources :work_orders do
    get :receipt, :on => :collection
    get :confirm_box_label, :on => :member
    post :print_box_label, :on => :member
    get :stock_in_label, :on => :member
  end

  root to: 'visitors#index' #首頁

  devise_for :users

  resources :users do
    get :autocomplete_user_email, :on => :collection
  end

end

app/models/stock_tran.rb
class StockTran < ActiveRecord::Base
  self.primary_key = :uuid
end

app/controllers/stock_trans_controller.rb
class StockTransController < ApplicationController
  before_action :set_stock_tran, only: [:show, :edit, :update, :destroy]

  # GET /stock_trans
  # GET /stock_trans.json
  def index
    @stock_trans = StockTran.all
  end

  # GET /stock_trans/1
  # GET /stock_trans/1.json
  def show
  end

  # GET /stock_trans/new
  def new
    @stock_tran = StockTran.new
  end

  # GET /stock_trans/1/edit
  def edit
  end

  # POST /stock_trans
  # POST /stock_trans.json
  def create
    @stock_tran = StockTran.new(stock_tran_params)

    respond_to do |format|
      if @stock_tran.save
        format.html { redirect_to @stock_tran, notice: 'Stock tran was successfully created.' }
        format.json { render :show, status: :created, location: @stock_tran }
      else
        format.html { render :new }
        format.json { render json: @stock_tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_trans/1
  # PATCH/PUT /stock_trans/1.json
  def update
    respond_to do |format|
      if @stock_tran.update(stock_tran_params)
        format.html { redirect_to @stock_tran, notice: 'Stock tran was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_tran }
      else
        format.html { render :edit }
        format.json { render json: @stock_tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_trans/1
  # DELETE /stock_trans/1.json
  def destroy
    @stock_tran.destroy
    respond_to do |format|
      format.html { redirect_to stock_trans_url, notice: 'Stock tran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stock_in
    master_id = params[:master_id] || ''
  end

  def in_process
    master_id = params[:master_id] || 0

    list = Barcode.where(:id => master_id)

    if list.empty?
      redirect_to in_stock_trans_url, notice: 'error message'
    else
      list.each do |barcode|
        if barcode.name = 'pallet'

          Barcode.where(parent_id: master_id).each do |bar|
            StockTran.create(
                {
                    :master_id   => bar.stock_master_id,
                    :barcode_id  => bar.id,
                    :lgort_old   => bar.lgort,
                    :lgort       => bar.lgort,
                    :status      => 'in',
                    :qty         => bar.menge,
                    :vbeln       => '',
                    :posnr       => '',
                    :meins       => bar.stock_master.meins,
                    :mjahr       => bar.stock_master.mjahr,
                    :mblnr       => bar.stock_master.mblnr, :zeile => bar.stock_master.zeile,
                    :aufnr       => bar.stock_master.aufnr, :prdln => '',
                    :ebeln       => bar.stock_master.ebeln, :ebelp => bar.stock_master.ebelp,
                    :mtype       => '',
                    :created_by  => current_user,
                    :created_ip  => request.remote_ip,
                    :created_mac => request.env['HTTP_X_FORWARDED_FOR'],
                    :updated_by  => current_user,
                    :updated_ip  => request.remote_ip, :updated_mac => ''
                }
            )
          end
          Barcode.where(parent_id: master_id).update_all({ status: 'in' })
        end
        barcode.status = 'in'
        barcode.save
      end
      redirect_to in_stock_trans_url, notice: 'success'
    end
  end

  def in

  end

  def out

    master_id = params[:master_id] || 0
#    lgort = params[:lgort] || ''

    if master_id != 0

      list = Barcode.where(:stock_master_id => master_id)

      list.each do |barcode|
        if barcode.id != 0 && barcode.menge == 0 && barcode.name == 'pallet' && barcode.status =='in'
          sum = Barcode.find_by_sql("select sum(menge) as menge from barcode where status='in' and parent_id= #{barcode.id}")

          l = StockMaster.where(:id => barcode.stock_master_id)

          @stock_tran = StockTran.new(:master_id => barcode.stock_master_id, :barcode_id => barcode.id, :lgort_old => barcode.lgort, :lgort => barcode.lgort, :status => 'out', :qty => sum[0].menge, :vbeln => '', :posnr => '', :meins => bar.meins, :mjahr => bar.mjahr, :mblnr => bar.mblnr, :zeile => bar.zeile, :aufnr => bar.aufnr, :prdln => '', :ebeln => bar.ebeln, :ebelp => bar.ebelp, :mtype => '', :created_by => current_user, :created_ip => request.remote_ip, :created_mac => request.env['HTTP_X_FORWARDED_FOR'], :updated_by => current_user, :updated_ip => request.remote_ip, :updated_mac => '')

          respond_to do |format|
            if @stock_tran.save

              alist = Barcode.find_by_sql("select * from barcode where status='in' and ( id=#{barcode.id} or parent_id = #{barcode.id} )")
              alist.each do |ali|
                bar      = Barcode.find_by_sql("select name,stock_master_id,parent_id,child,lgort,status,menge from barcode where id=#{ali.id}")
                @barcode = Barcode.new(:name => bar[0].name, :stock_master_id => bar[0].stock_master_id, :parent_id => bar[0].parent_id, :child => bar[0].child, :lgort => bar[0].lgort, :status => 'out', :menge => bar[0].menge)
                @barcode.save
              end
              format.html { redirect_to @stock_tran, notice: 'Stock tran was successfully created.' }
              format.json { render :show, status: :created, location: @stock_tran }
            else
              format.html { render :new }
              format.json { render json: @stock_tran.errors, status: :unprocessable_entity }
            end
          end

        else
          if barcode.id != 0 && barcode.menge != 0 && barcode.name == 'box' && barcode.status =='in'

            sum = Barcode.find_by_sql("select sum(menge) as menge from barcode where status='in' and parent_id= #{barcode.id}")

            l = StockMaster.where(:id => barcode.stock_master_id)

            @stock_tran = StockTran.new(:master_id => barcode.stock_master_id, :barcode_id => barcode.id, :lgort_old => barcode.lgort, :lgort => barcode.lgort, :status => 'out', :qty => sum[0].menge, :vbeln => '', :posnr => '', :meins => bar.meins, :mjahr => bar.mjahr, :mblnr => bar.mblnr, :zeile => bar.zeile, :aufnr => bar.aufnr, :prdln => '', :ebeln => bar.ebeln, :ebelp => bar.ebelp, :mtype => '', :created_by => current_user, :created_ip => request.remote_ip, :created_mac => request.env['HTTP_X_FORWARDED_FOR'], :updated_by => current_user, :updated_ip => request.remote_ip, :updated_mac => '')

            respond_to do |format|
              if @stock_tran.save
                alist = Barcode.find_by_sql("select * from barcode where status='in' and ( id=#{barcode.id} or parent_id = #{barcode.id} ) ")
                alist.each do |ali|
                  bar      = Barcode.find_by_sql("select name,stock_master_id,parent_id,child,lgort,status,menge from barcode where id=#{ali.id}")
                  @barcode = Barcode.new(:name => bar[0].name, :stock_master_id => bar[0].stock_master_id, :parent_id => bar[0].parent_id, :child => bar[0].child, :lgort => bar[0].lgort, :status => 'out', :menge => bar[0].menge)
                  @barcode.save
                end
                format.html { redirect_to @stock_tran, notice: 'Stock tran was successfully created.' }
                format.json { render :show, status: :created, location: @stock_tran }
              else
                format.html { render :new }
                format.json { render json: @stock_tran.errors, status: :unprocessable_entity }
              end
            end

          end
        end
      end
    end


#    master_id = params[:master_id] || 0
#    if master_id != 0

#      list = Barcode.where(:stock_master_id=>master_id)

#      list.each do | barcode |
#        if barcode.id != 0 && barcode.menge == 0 && barcode.name == 'pallet' && barcode.status =='in'
#          sum = Barcode.find_by_sql("select sum(menge) as menge from barcode where status='in' and parent_id= #{barcode.id}")

#          l = StockMaster.where(:id=>barcode.stock_master_id)

#          @stock_tran = StockTran.new(:master_id=>barcode.stock_master_id, :barcode_id=>barcode.id, :lgort_old=>barcode.lgort,:lgort=>barcode.lgort, :status=>'out', :qty=>sum[0].menge, :vbeln=>'', :posnr=>'', :meins=>bar.meins, :mjahr=>bar.mjahr, :mblnr=>bar.mblnr, :zeile=>bar.zeile, :aufnr=>bar.aufnr, :prdln=>'', :ebeln=>bar.ebeln, :ebelp=>bar.ebelp, :mtype=>'', :created_by=>current_user, :created_ip=>request.remote_ip, :created_mac=>request.env['HTTP_X_FORWARDED_FOR'], :updated_by=>current_user, :updated_ip=>request.remote_ip, :updated_mac=>'')

#          respond_to do |format|
#            if @stock_tran.save

#              alist = Barcode.find_by_sql("select * from barcode where status='in' and (id=#{barcode.id} or parent_id = #{barcode.id}) ")
#              alist.each do | ali |
#                bar = Barcode.find_by_sql("select name,stock_master_id,parent_id,child,lgort,status,menge from barcode where id=#{ali.id}")
#                @barcode = Barcode.new(:name=>bar[0].name,:stock_master_id=>bar[0].stock_master_id,:parent_id=>bar[0].parent_id,:child=>bar[0].child,:lgort=>bar[0].lgort,:status=>'out',:menge=>bar[0].menge)
#                @barcode.save
#              end
#              format.html { redirect_to @stock_tran, notice: 'Stock tran was successfully created.' }
#              format.json { render :show, status: :created, location: @stock_tran }
#            else
#              format.html { render :new }
#              format.json { render json: @stock_tran.errors, status: :unprocessable_entity }
#            end
#          end

#        else if barcode.id != 0 && barcode.menge != 0 && barcode.name == 'box' && barcode.status =='in'
#           sum = Barcode.find_by_sql("select sum(menge) as menge from barcode where status='in' and parent_id= #{barcode.id}")

#           l = StockMaster.where(:id=> barcode.stock_master_id)

app/helpers/stock_trans_helper.rb
module StockTransHelper
end

app/views/stock_trans/_form.html.haml
= simple_form_for(@stock_tran) do |f|
  = f.error_notification

  .form-inputs
    = f.input :master_id
    = f.input :barcode_id
    = f.input :lgort_old
    = f.input :lgort
    = f.input :status
    = f.input :qty
    = f.input :vbeln
    = f.input :posnr
    = f.input :meins
    = f.input :mjahr
    = f.input :mblnr
    = f.input :zeile
    = f.input :aufnr
    = f.input :prdln
    = f.input :ebeln
    = f.input :ebelp
    = f.input :mtype
    = f.input :created_by
    = f.input :created_ip
    = f.input :created_mac
    = f.input :updated_by
    = f.input :updated_ip
    = f.input :updated_mac

  .form-actions
    .clearfix
    = button_tag class: 'btn btn-danger', type: 'button', onclick: "$(this).button('loading');this.form.submit();", data:{loading_text: t('saving')} do
      %span.glyphicon.glyphicon-floppy-save
      = t('save')

app/views/stock_trans/edit.html.haml
%h3= t('edit_stock_tran')
%h5
  = link_to t('show'), @stock_tran
  \|
  = link_to t('back'), stock_trans_path

= render 'form'

%h5
  = link_to t('show'), @stock_tran
  \|
  = link_to t('back'), stock_trans_path

app/views/stock_trans/in.html.haml
%h5= '入库'

= form_tag(in_process_stock_trans_url , method: 'get', class: 'form-inline') do
  = text_field_tag :master_id, nil, placeholder: t('attributes.master_id'), class: 'form-control input-sm', value: params[:master_id]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search

app/views/stock_trans/index.html.haml
%h3= t('attributes.stock_tran')

%h5
  = link_to t('new_stock_tran'), new_stock_tran_path

= form_tag(stock_trans_url, method: 'get', class: 'form-inline') do
  = text_field_tag :name, nil, placeholder: t('attributes.name'), class: 'form-control input-sm', value: params[:name]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search

.table-responsive
  %table.table.table-hover.table-condensed.table-bordered
    %thead
      %tr
        %th= t('action')
        %th= t('attributes.master_id')
        %th= t('attributes.barcode_id')
        %th= t('attributes.lgort_old')
        %th= t('attributes.lgort')
        %th= t('attributes.status')
        %th= t('attributes.qty')
        %th= t('attributes.vbeln')
        %th= t('attributes.posnr')
        %th= t('attributes.meins')
        %th= t('attributes.mjahr')
        %th= t('attributes.mblnr')
        %th= t('attributes.zeile')
        %th= t('attributes.aufnr')
        %th= t('attributes.prdln')
        %th= t('attributes.ebeln')
        %th= t('attributes.ebelp')
        %th= t('attributes.mtype')
        %th= t('attributes.created_by')
        %th= t('attributes.created_ip')
        %th= t('attributes.created_mac')
        %th= t('attributes.updated_by')
        %th= t('attributes.updated_ip')
        %th= t('attributes.updated_mac')
    %tbody
      - @stock_trans.each do |stock_tran|
        %tr
          %td
            = link_to t('edit'), edit_stock_tran_path(stock_tran)
            |
            = link_to t('delete'), stock_tran, :method => :delete, :data => { :confirm => t('confirm_delete')}

          %td= stock_tran.master_id
          %td= stock_tran.barcode_id
          %td= stock_tran.lgort_old
          %td= stock_tran.lgort
          %td= stock_tran.status
          %td= stock_tran.qty
          %td= stock_tran.vbeln
          %td= stock_tran.posnr
          %td= stock_tran.meins
          %td= stock_tran.mjahr
          %td= stock_tran.mblnr
          %td= stock_tran.zeile
          %td= stock_tran.aufnr
          %td= stock_tran.prdln
          %td= stock_tran.ebeln
          %td= stock_tran.ebelp
          %td= stock_tran.mtype
          %td= stock_tran.created_by
          %td= stock_tran.created_ip
          %td= stock_tran.created_mac
          %td= stock_tran.updated_by
          %td= stock_tran.updated_ip
          %td= stock_tran.updated_mac

%h5
  = link_to t('new_stock_tran'), new_stock_tran_path

= paginate @stock_trans unless @stock_trans.empty?

app/views/stock_trans/new.html.haml
%h3= t('new_stock_tran')

%h5
  = link_to t('back'), stock_trans_path

= render 'form'

%h5
  = link_to t('back'), stock_trans_path

app/views/stock_trans/out.html.haml
%h5= '出库'

= form_tag(out_stock_trans_url , method: 'get', class: 'form-inline') do
  = text_field_tag :master_id, nil, placeholder: t('attributes.master_id'), class: 'form-control input-sm', value: params[:master_id]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search

app/views/stock_trans/show.html.haml
%h3= t('attributes.stock_tran')
%h5
  = link_to t('edit'), edit_stock_tran_path(@stock_tran)
  \|
  = link_to t('back'), stock_trans_path

= render partial: 'layouts/show', :locals => {object: @stock_tran}

%h5
  = link_to t('edit'), edit_stock_tran_path(@stock_tran)
  \|
  = link_to t('back'), stock_trans_path

app/views/stock_trans/stock_in.html.haml
%h3= '入库'

= form_tag(stock_in_stock_tran_url , method: 'get', class: 'form-inline') do
  = text_field_tag :master_id, nil, placeholder: t('attributes.master_id'), class: 'form-control input-sm', value: params[:master_id]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search