config/routes.rb
Rails.application.routes.draw do

  resources :printers

  resources :barcodes do
    get :scan, on: :collection
    get :unlink_pallet, on: :member
    get :in, on: :collection
    get :in_scan, on: :collection
    post :in_putaway, on: :collection
    get :repeat_printer, on: :collection
    get :printer_label, on: :collection
  end

  resources :stock_masters
  resources :stock_trans do
    get :in, :on => :collection
    get :in_scan, :on => :collection
    get :out, :on => :collection
  end

  resources :work_orders do
    get :receipt, :on => :collection
    get :confirm_box_label, :on => :member
    post :print_box_label, :on => :member
    get :stock_in_label, :on => :member
  end

  root to: 'visitors#index' #首頁

  devise_for :users

  resources :users do
    get :autocomplete_user_email, :on => :collection
  end

end

app/models/barcode.rb
class Barcode < ActiveRecord::Base
  self.primary_key = :uuid
  belongs_to :stock_master
  belongs_to :parent, class_name: 'Barcode', foreign_key: 'parent_id', primary_key: 'uuid'

  def self.test
    str =
        "
        ^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4~SD15^JUS^LRN^CI0^XZ
        ^XA
        ^MMT
        ^PW900
        ^LL0600
        ^LS0
        ^FT20,494^A0N,42,196^FH\^FDfff^FS
        ^FT20,417^A0N,42,196^FH\^FDfff^FS
        ^FT22,339^A0N,42,196^FH\^FDfff^FS
        ^FT25,267^A0N,42,196^FH\^FDfff^FS
        ^FT28,185^A0N,42,196^FH\^FDfff^FS
        ^FT28,91^A0N,42,196^FH\^FDfff^FSb
        ^BY4,3,236^FT594,264^BCN,,Y,N
        ^FD>;123456^FS
        ^FT344,128^A0N,42,40^FH\^FDdfdsf^FS
        ^PQ1,0,1,Y^XZ
    "
    s = TCPSocket.new('172.91.8.56','9100')
    s.write str
    s.close
  end

  def self.finish_goods_label(hash)
    lab1 = "
      ^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4~SD20^JUS^LRN^CI0^XZ
      ^XA
      ^MMT
      ^PW945
      ^LL0768
      ^LS0
      ^FT189,340^BQN,2,7
      ^FDLA,#{hash[:id]}^FS
      ^FT726,350^A0B,33,33^FH\^FDDate^FS
      ^FT804,349^A0B,75,74^FH\^FD#{hash[:date]}^FS
      ^FT306,763^A0B,33,33^FH\^FDDate Code^FS
      ^FT394,763^A0B,75,74^FH\^FD#{hash[:date_code]}^FS
      ^FT435,225^A0B,33,33^FH\^FDPlant^FS
      ^FT525,225^A0B,75,74^FH\^FD#{hash[:factory]}^FS
      ^FT449,763^A0B,33,33^FH\^FDLot No^FS
      ^FT532,763^A0B,75,74^FH\^FD#{hash[:lot_no]}^FS
      ^FT187,763^A0B,33,33^FH\^FDMO^FS
      ^FT725,768^A0B,33,33^FH\^FDQuantity^FS
      ^FT252,763^A0B,75,74^FH\^FD#{hash[:mo]}^FS
      ^FT588,768^A0B,33,33^FH\^FDLEI Product No^FS
    "
    lab2 = "
      ^FT914,768^A0B,28,50^FH\^FD#{hash[:name]}^FS
      ^FT930,532^A0B,55,67^FH\^FD**#{hash[:seq]}**^FS
      ^FT867,768^A0B,28,50^FH\^FD#{hash[:name_parent]}^FS
      ^FT865,425^A0B,38,50^FH\^FD**#{hash[:seq_parent]}**^FS
    "
    if hash[:seq_parent].blank?
      lab2 = "
      ^FT901,768^A0B,50,50^FH\^FD#{hash[:name]}^FS
      ^FT901,414^A0B,50,50^FH\^FD**#{hash[:seq]}**^FS
     "

    end
    lab3 = "
      ^FT803,768^A0B,75,74^FH\^FD#{hash[:qty]} #{hash[:meins]}^FS
      ^FT674,768^A0B,75,74^FH\^FD#{hash[:product_no]}^FS
      ^FT135,763^A0B,75,74^FH\^FDLeader Electronics Inc^FS
      ^PQ1,0,1,Y^XZ
    "
    lab = lab1 + lab2 + lab3
    finish_goods_label_end lab
  end

  def self.finish_goods_label_end(str)
     str
  end

  def self.finish_goods_label_old(hash)
    "
      ^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4~SD20^JUS^LRN^CI0^XZ
      ^XA
      ^MMT
      ^PW945
      ^LL0768
      ^LS0
      ^FT154,276^BQN,2,7
      ^FDLA,http://bc.l-e-i.com:3088/bc/#{hash[:id]}^FS
      ^FT695,345^A0B,33,33^FH\^FDDate^FS
      ^FT773,344^A0B,75,74^FH\^FD#{hash[:date]}^FS
      ^FT270,763^A0B,33,33^FH\^FDDate Code^FS
      ^FT359,763^A0B,75,74^FH\^FD#{hash[:date_code]}^FS
      ^FT414,763^A0B,33,33^FH\^FDLot No^FS
      ^FT496,763^A0B,75,74^FH\^FD#{hash[:lot_no]}^FS
      ^FT151,763^A0B,33,33^FH\^FDMO^FS
      ^FT694,763^A0B,33,33^FH\^FDQuantity^FS
      ^FT217,763^A0B,75,74^FH\^FD#{hash[:mo]}^FS
      ^FT557,763^A0B,33,33^FH\^FDLEI Product No^FS
      ^FT772,763^A0B,75,74^FH\^FD#{hash[:qty]}^FS
      ^FT644,763^A0B,75,74^FH\^FD#{hash[:product_no]}^FS
      ^FT100,763^A0B,75,74^FH\^FDLeader Electronics Inc^FS
      ^BY5,3,94^FT885,768^B3B,N,,Y,N
      ^FD#{hash[:id]}^FS
      ^PQ1,0,1,Y^XZ
    "
  end

  def self.in_scan(uuid, storage)
    sql = "
      select a.uuid,a.seq,a.name,a.menge,b.matnr,b.charg
        from barcode a join stock_master b on b.uuid = a.stock_master_id
        where a.uuid = ?
    "
    rows = Barcode.find_by_sql [sql, params[:barcode]]

    if rows.present?
      row = rows.first
    end
  end

end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  before_action :set_barcode, only: [:show, :edit, :update, :destroy]

  # GET /barcodes
  # GET /barcodes.json
  def index
    @barcodes = Barcode.all
  end

  def scan
    if params[:barcode].present?
      @barcode = Barcode.find_by_uuid(params[:barcode]) if params[:barcode].size == 32
      @barcode = Barcode.find_by_seq(params[:barcode]) if @barcode.blank?
    end
    if @barcode.present?
      if @barcode.name.eql?('box')
        @qty = @barcode.menge
      else
        @qty = Barcode.where(parent_id: @barcode.uuid).sum(:menge)
        @barcodes = Barcode.where(parent_id: @barcode.uuid).select(:seq,:menge)
      end
    end
  end

  # GET /barcodes/1
  # GET /barcodes/1.json
  def show
  end

  # GET /barcodes/new
  def new
    @barcode = Barcode.new
  end

  # GET /barcodes/1/edit
  def edit
  end

  # POST /barcodes
  # POST /barcodes.json
  def create
    @barcode = Barcode.new(barcode_params)

    respond_to do |format|
      if @barcode.save
        format.html { redirect_to @barcode, notice: 'Barcode was successfully created.' }
        format.json { render :show, status: :created, location: @barcode }
      else
        format.html { render :new }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barcodes/1
  # PATCH/PUT /barcodes/1.json
  def update
    respond_to do |format|
      if @barcode.update(barcode_params)
        format.html { redirect_to @barcode, notice: 'Barcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @barcode }
      else
        format.html { render :edit }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barcodes/1
  # DELETE /barcodes/1.json
  def destroy
    @barcode.destroy
    respond_to do |format|
      format.html { redirect_to barcodes_url, notice: 'Barcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def unlink_pallet
    barcode = Barcode.find params[:id]
    barcode.parent_id = ''
    barcode.save
    redirect_to scan_barcodes_url(barcode: barcode.uuid)
  end

  def in

  end

  def in_scan
    rows    = []
    barcode = Barcode.find_by_uuid params[:barcode]
    if barcode.present?
      uuid = barcode.parent_id.size == 32 ? barcode.parent_id : barcode.uuid
      sql  = "
          select a.uuid,a.seq,a.name,a.menge,b.matnr,b.charg
            from barcode a join stock_master b on b.uuid = a.stock_master_id
            where a.parent_id = ? or a.uuid = ?
        "
      rows = Barcode.find_by_sql [sql, uuid, uuid]
    end
    render json: rows
  end

  def in_putaway
    barcodes = Barcode.includes(:stock_master).joins(:stock_master)
                   .where(uuid: params[:uuid].split(','))

    response     = {
        barcode_uuid: 'success'
    }
    barcode_uuid = ''
    StockTran.transaction do
      begin
        barcodes.each { |barcode|
          barcode_uuid = barcode.uuid
          StockTran.create({
                               master_id:   barcode.stock_master_id,
                               barcode_id:  barcode.uuid,
                               lgort_old:   barcode.storage.blank? ? barcode.lgort : barcode.storage,
                               lgort:       params[:storage],
                               status:      barcode.status,
                               menge:       barcode.menge,
                               vbeln:       '',
                               posnr:       '',
                               meins:       barcode.stock_master.meins,
                               mjahr:       barcode.stock_master.mjahr,
                               mblnr:       barcode.stock_master.mblnr,
                               zeile:       barcode.stock_master.zeile,
                               aufnr:       barcode.stock_master.aufnr,
                               prdln:       barcode.stock_master.prdln,
                               ebeln:       barcode.stock_master.ebeln,
                               ebelp:       barcode.stock_master.ebelp,
                               mtype:       'in_putway',
                               created_by:  current_user.email,
                               created_ip:  request.ip,
                               created_mac: '',
                               updated_by:  current_user.email,
                               updated_ip:  request.ip,
                               updated_mac: '',
                           })
          barcode.status  = 'putaway'
          barcode.storage = params[:storage]
          barcode.save
        }
      rescue Exception => e
        response = {
            barcode_uuid:  barcode_uuid,
            error_message: e.message
        }
      end
    end
    render json: response
  end

  def repeat_printer
    if params[:barcode].present?
      @barcode = Barcode.find_by_uuid(params[:barcode])
      @barcode = Barcode.find_by_seq(params[:barcode]) if @barcode.blank?
    end
  end

  def printer_label
    barcode = Barcode.where(:uuid => params[:uuid]).first
    stock_master = StockMaster.where(:uuid => barcode.stock_master_id).first

    printer = Printer.find params[:printer_id]
    socket = TCPSocket.new(printer.ip, printer.port)

    hash = {
        :id => barcode.id,
        :date => stock_master.budat,
        :date_code => stock_master.datecode,
        :lot_no => stock_master.charg,
        :mo => stock_master.aufnr,
        :qty => barcode.menge,
        :product_no => stock_master.matnr,
        :seq => barcode.seq,
        :name => barcode.name.blank? ? '' : barcode.name[0].upcase,
        :meins => stock_master.meins,
        :seq_parent => (barcode.parent_id != 0 && barcode.name[0].upcase.eql?('B')) ? barcode.parent.seq : '',
        :name_parent => (barcode.parent_id != 0 && barcode.name[0].upcase.eql?('P')) ? 'P' : barcode.parent.name[0].upcase,
        :factory => stock_master.werks
    }
    zpl_command = Barcode.finish_goods_label hash
    socket.write zpl_command
    socket.close
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_barcode
    @barcode = Barcode.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def barcode_params
    params.require(:barcode).permit(:storage, :name, :stock_master_id, :parent_id, :child, :lgort, :status, :menge)
  end
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/views/barcodes/_form.html.haml
= simple_form_for(@barcode) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :stock_master_id
    = f.input :parent_id
    = f.input :child
    = f.input :lgort
    = f.input :status
    = f.input :menge

  .form-actions
    .clearfix
    = button_tag class: 'btn btn-danger', type: 'button', onclick: "$(this).button('loading');this.form.submit();", data:{loading_text: t('saving')} do
      %span.glyphicon.glyphicon-floppy-save
      = t('save')

app/views/barcodes/edit.html.haml
%h3= t('edit_barcode')
%h5
  = link_to t('show'), @barcode
  \|
  = link_to t('back'), barcodes_path

= render 'form'

%h5
  = link_to t('show'), @barcode
  \|
  = link_to t('back'), barcodes_path

app/views/barcodes/in.html.haml
%link{href: '/js/DataTables/datatables.min.css', rel:'stylesheet'}
%script{src: '/js/DataTables/datatables.min.js'}

.panel.panel-default
  .panel-heading
    倉庫掃描收貨及上架
    .pull-right
      %a#InitPageLink{href:'#'}
        清除資料
  .panel-body{style:'padding-bottom: 0px;'}
    = form_tag(in_scan_barcodes_url, method: 'get', class: 'form-horizontal', remote: true, id:'form_id') do
      .form-group
        .col-xs-12
          = text_field_tag :storage, nil, placeholder: t('attributes.storage'), class: 'form-control', value: params[:storage], id: 'storage'
      .form-group
        .col-xs-12
          = text_field_tag :barcode, nil,placeholder: t('attributes.barcode'), class: 'form-control', value: '', id: 'barcode'

    總數量:<input type='text' id='qty' disabled='disabled' value='0' size='5px'/>
    總箱量:<input type='text' id='box' disabled='disabled' value='0' size='5px'/>
    總棧板:<input type='text' id='pallet' disabled='disabled' value='0' size='5px'/>
    <input id='putaway' class="btn btn-primary btn-sm" type="button">
  .table-responsive
    %table.table.table-striped.small.table-condensed#grid_view{width:'100%'}

:javascript
  var dataSet = [];

  function init_page(){
    $('#qty').val('0');
    $('#box').val('0');
    $('#pallet').val('0');
    $('#putaway').attr("disabled", false);
    $('#putaway').attr("value", '確認上貨架');
    $('#grid_view').DataTable().clear().draw();
  }

  $(document).ready(function () {

    if ($('#storage').val() == ""){
      $('#storage').focus();
    }
    else{
      $('#barcode').focus();
    }

    $('#barcode').focus(function(){
      if ($('#storage').val() == ""){
        alert('儲存架位置, 不能為空!')
        $('#storage').focus();
      }
    });

     $('#grid_view').DataTable( {
        data: dataSet,
        info: false,
        ordering: true,
        paging: false,
        searching: false,
        scrollY: '50vh',
        scrollX: true,
        scrollCollapse: true,
        columns: [
            { title: "UUID" },
            { title: "標籤" },
            { title: "產品" },
            { title: "數量" },
            { title: "批次" },
            { title: "包裝" }
        ],
        columnDefs: [
          {
            targets: [0],
            visible: false,
            searchable: false
          }
        ]
    });

    $('#grid_view tbody').on( 'click', 'button.close', function () {
      if(confirm("确定要清空数据吗？")){
        table_row = $('#grid_view').DataTable().row($(this).parents('tr'));
        $('#qty').val(parseFloat($('#qty').val()) - table_row.data()[3])
        if (table_row.data()[5] == 'P'){
          $('#pallet').val(parseInt($('#pallet').val()) - 1)
        }
        else{
          $('#box').val(parseInt($('#box').val()) - 1)
        }
        $('#grid_view').DataTable()
          .row($(this).parents('tr'))
          .remove()
          .draw();
      };
    });

    $('#barcode').change(function(){
      if ($('#barcode').val() != ""){
        $.ajax({
          url: 'in_scan',
          data: {
            barcode: $('#barcode').val()
          }
        }).done(function(json){
          data = $('#grid_view').DataTable().data()
          for (index = 0; index < json.length; index++) {
            found = false;
            for(i = 0; i < data.length; i++){
              if (data[i][0] == json[index].uuid){
                found = true;
                break;
              }
            }
            if (found == false) {
              $('#grid_view').DataTable().row.add([
                json[index].uuid,
                json[index].seq,
                json[index].matnr,
                json[index].menge,
                json[index].charg,
                json[index].name[0].toUpperCase(),
              ]).draw(false);
              $('#qty').val(parseFloat($('#qty').val()) + json[index].menge)
              if (json[index].name[0].toUpperCase() == 'P'){
                $('#pallet').val(parseInt($('#pallet').val()) + 1)
              }
              else{
                $('#box').val(parseInt($('#box').val()) + 1)
              }
            }
          }
        });
      }
      $('#barcode').val("");
    });

    $('#InitPageLink').click(function(){
      init_page();
    });

    $('#putaway').click(function(){
      $(this).attr("disabled", true);
      $(this).attr("value", '保存中...');
      _uuid = '';
      dataStore = $('#grid_view').DataTable().data();
      for(i = 0; i < dataStore.length; i++){
        if (_uuid != ''){
          _uuid = _uuid + ',';
        }
        _uuid = _uuid + dataStore[i][0]
      }

      ajax = $.ajax({
        url: 'in_putaway',
        method: 'post',
        data: {
          uuid: _uuid,
          storage: $('#storage').val()
        }
      });
      ajax.done(function(response){
        if (response.barcode_uuid == 'success'){
          alert("倉庫掃描收貨及上架成功");
          init_page();
        }
        else{
          alert("注意系統錯誤, 請再一次上傳\n\nbarcode_uuid:"+response.barcode_uuid + "\n" +response.error_message);
          $('#putaway').attr("disabled", false);
          $('#putaway').attr("value", '確認上貨架');
        }
      });
    });

    init_page();

  })

app/views/barcodes/index.html.haml
%h3= t('attributes.barcode')

%h5
  = link_to t('new_barcode'), new_barcode_path

= form_tag(barcodes_url, method: 'get', class: 'form-inline') do
  = text_field_tag :name, nil, placeholder: t('attributes.name'), class: 'form-control input-sm', value: params[:name]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search

.table-responsive
  %table.table.table-hover.table-condensed.table-bordered
    %thead
      %tr
        %th= t('action')
        %th= t('attributes.name')
        %th= t('attributes.stock_master_id')
        %th= t('attributes.parent_id')
        %th= t('attributes.child')
        %th= t('attributes.lgort')
        %th= t('attributes.status')
        %th= t('attributes.menge')
    %tbody
      - @barcodes.each do |barcode|
        %tr
          %td
            = link_to t('edit'), edit_barcode_path(barcode)
            |
            = link_to t('delete'), barcode, :method => :delete, :data => { :confirm => t('confirm_delete')}

          %td= barcode.name
          %td= barcode.stock_master_id
          %td= barcode.parent_id
          %td= barcode.child
          %td= barcode.lgort
          %td= barcode.status
          %td= barcode.menge

%h5
  = link_to t('new_barcode'), new_barcode_path

= paginate @barcodes unless @barcodes.empty?

app/views/barcodes/new.html.haml
%h3= t('new_barcode')

%h5
  = link_to t('back'), barcodes_path

= render 'form'

%h5
  = link_to t('back'), barcodes_path

app/views/barcodes/printer_label.html.haml
.panel.panel-default
  .panel-heading
    條碼信息查詢
  .panel-body{style:'padding-bottom: 0px;'}
    = form_tag(repeat_printer_barcodes_url, method: 'get', class: 'form-horizontal', id:'form_id') do
      .form-group
        .col-xs-12
          = text_field_tag :barcode, nil,placeholder: t('attributes.barcode'), class: 'form-control', value:'', id: 'barcode'
    %hr
    - if @barcode.present?
      %dl.dl-horizontal
        %dt= t('attributes.barcode')
        %dd= @barcode.seq
        %dt= t('attributes.matnr')
        %dd= @barcode.stock_master.matnr
        %dt= t('attributes.aufnr')
        %dd= @barcode.stock_master.aufnr
        %dt= 'DCODE'
        %dd= @barcode.stock_master.datecode
        %dt= t('attributes.charg')
        %dd= @barcode.stock_master.charg
        %dt= "選擇打印機"

        = form_tag(printer_label_barcodes_url, method: 'get', class: 'form-inline', id:'form_id') do
          = hidden_field_tag :uuid,@barcode.uuid
          = select_tag 'printer_id', options_from_collection_for_select(Printer.all.select(:uuid,:code), 'uuid', 'code', current_user.printer_id), class: 'select optional form-control'
          = button_tag class: 'btn btn-primary btn-form-submit btn-lg', type: 'button' do
            打印外箱條碼標籤
            %span.glyphicon.glyphicon-print

app/views/barcodes/repeat_printer.html.haml
.panel.panel-default
  .panel-heading
    條碼信息查詢
  .panel-body{style:'padding-bottom: 0px;'}
    = form_tag(repeat_printer_barcodes_url, method: 'get', class: 'form-horizontal', id:'form_id') do
      .form-group
        .col-xs-12
          = text_field_tag :barcode, nil,placeholder: t('attributes.barcode'), class: 'form-control', value:'', id: 'barcode'
    %hr
    - if @barcode.present?
      %dl.dl-horizontal
        %dt= t('attributes.barcode')
        %dd= @barcode.seq
        %dt= t('attributes.matnr')
        %dd= @barcode.stock_master.matnr
        %dt= t('attributes.aufnr')
        %dd= @barcode.stock_master.aufnr
        %dt= 'DCODE'
        %dd= @barcode.stock_master.datecode
        %dt= t('attributes.charg')
        %dd= @barcode.stock_master.charg
        %dt= "選擇打印機"

        = form_tag(printer_label_barcodes_url, method: 'get', class: 'form-inline', id:'form_id') do
          = hidden_field_tag :uuid,@barcode.uuid
          = select_tag 'printer_id', options_from_collection_for_select(Printer.all.select(:uuid,:code), 'uuid', 'code', current_user.printer_id), class: 'select optional form-control'
          = button_tag class: 'btn btn-primary btn-form-submit btn-lg', type: 'button' do
            打印外箱條碼標籤
            %span.glyphicon.glyphicon-print

app/views/barcodes/scan.html.haml
.panel.panel-default
  .panel-heading
    條碼信息查詢及解除棧板
  .panel-body{style:'padding-bottom: 0px;'}
    = form_tag(scan_barcodes_url, method: 'get', class: 'form-horizontal', id:'form_id') do
      .form-group
        .col-xs-12
          = text_field_tag :barcode, nil,placeholder: t('attributes.barcode'), class: 'form-control', value:'', id: 'barcode'
    %hr
    - if @barcode.present?
      %dl.dl-horizontal.mobile
        %dt= t('attributes.barcode')
        %dd= @barcode.seq
        %dt= t('attributes.matnr')
        %dd= @barcode.stock_master.matnr
        %dt= t('attributes.charg')
        %dd= @barcode.stock_master.charg
        %dt= t('attributes.maktx')
        %dd= @barcode.stock_master.maktx
        %dt= t('attributes.matkl')
        %dd= @barcode.stock_master.matkl
        %dt= t('attributes.aufnr')
        %dd= @barcode.stock_master.aufnr
        %dt= t('attributes.budat')
        %dd= @barcode.stock_master.budat
        %dt= 'DCODE'
        %dd= @barcode.stock_master.datecode
        %dt= t('attributes.werks')
        %dd= @barcode.stock_master.werks
        %dt= t('attributes.mblnr')
        %dd
          = @barcode.stock_master.mjahr
          = @barcode.stock_master.mblnr
          = @barcode.stock_master.zeile
        %dt= t('attributes.lgort')
        %dd= @barcode.storage.present? ? @barcode.storage : @barcode.lgort
        %dt= t('attributes.container')
        %dd= @barcode.name.upcase
        %dt= t('attributes.menge')
        %dd
          = @qty
          = @barcode.stock_master.meins
        - if @barcode.parent.present?
          %dt= t('attributes.pallet_cnt')
          %dd
            = @barcode.parent.seq
            = link_to t('attributes.unlink_pallet'), unlink_pallet_barcode_url(@barcode.uuid)
    %hr
    - if @barcodes.present?
      = "此棧板上有#{@barcodes.size}箱"
      .table-responsive
        %table.table.table-striped.table-condensed.small
          %thead
            %tr
              %th
              %th= t('attributes.barcode')
              %th= t('attributes.menge')
          %tbody
            - i = 0
            - @barcodes.each do |row|
              - i += 1
              %tr
                %td= i
                %td= row.seq
                %td
                  = row.menge
                  = @barcode.stock_master.meins

app/views/barcodes/show.html.haml
%h3= t('attributes.barcode')
%h5
  = link_to t('edit'), edit_barcode_path(@barcode)
  \|
  = link_to t('back'), barcodes_path

= render partial: 'layouts/show', :locals => {object: @barcode}

%h5
  = link_to t('edit'), edit_barcode_path(@barcode)
  \|
  = link_to t('back'), barcodes_path