config/routes.rb
Rails.application.routes.draw do

  resources :printers

  resources :barcodes do
    get :scan, on: :collection
    get :unlink_pallet, on: :member
    get :in, on: :collection
    get :in_scan, on: :collection
    post :in_putaway, on: :collection
    get :repeat_printer, on: :collection
    get :printer_label, on: :collection
  end

  resources :stock_masters
  resources :stock_trans do
    get :in, :on => :collection
    get :in_scan, :on => :collection
    get :out, :on => :collection
  end

  resources :work_orders do
    get :receipt, :on => :collection
    get :confirm_box_label, :on => :member
    post :print_box_label, :on => :member
    get :stock_in_label, :on => :member
  end

  root to: 'visitors#index' #首頁

  devise_for :users

  resources :users do
    get :autocomplete_user_email, :on => :collection
  end

end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController

  def receipt
    budat = params[:budat] || Time.now.strftime('%Y%m%d')
    usnam = params[:usnam] || ''
    werks = params[:werks] || ''
    matnr = params[:matnr] || ''
    aufnr = params[:aufnr] || ''

    if current_user.territory == 'TX'
      t_werks = "and werks in (#{Figaro.env.tx_sql_werks})"
    elsif current_user.territory == 'DT'
      t_werks = "and werks in (#{Figaro.env.dt_sql_werks})"
    end

    sql = "
      select a.rowid,
        a.mblnr,a.mjahr,b.zeile,a.budat,a.cputm,a.usnam,
        b.matnr,d.maktx,b.werks,b.lgort,b.charg,f.atwrt,b.menge,b.meins,
        b.aufnr
      from sapsr3.mkpf a
        join sapsr3.mseg b on b.mandt=a.mandt and b.mblnr=a.mblnr and b.aufnr <> ' '
        join sapsr3.mara c on c.mandt=b.mandt and c.matnr=b.matnr
        join sapsr3.makt d on d.mandt=c.mandt and d.matnr=c.matnr and d.spras='M'
        join sapsr3.mch1 e on e.mandt=b.mandt and e.matnr=b.matnr and e.charg=b.charg
        join sapsr3.ausp f on f.mandt=e.mandt and f.objek=e.cuobj_bm and f.atinn='0000000816' and f.klart='023'
      where a.mandt='168' and a.vgart = 'WR' and a.budat = '#{budat}'
        and usnam like '%#{usnam}%' and werks like '%#{werks}%' and matnr like '%#{matnr}%'
        and aufnr like '%#{aufnr}%'
        #{t_werks}
      order by mjahr desc, mblnr desc
    "
    @list = Sapdb.find_by_sql sql

  end

  def confirm_box_label
    @record = StockMaster.get_label_info params[:id]
  end

  def print_box_label
    StockMaster.print_box_label(params)
    redirect_to receipt_work_orders_path
  end

  def stock_in_label
    #redirect_to new_stock_tran_path
    redirect_to stock_in_stock_tran_path
  end
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/_form.html.haml
= simple_form_for(@work_order) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    .clearfix
    = button_tag class: 'btn btn-danger', type: 'button', onclick: "$(this).button('loading');this.form.submit();", data:{loading_text: t('saving')} do
      %span.glyphicon.glyphicon-floppy-save
      = t('save')

app/views/work_orders/confirm_box_label.html.haml
.table-responsive
  %table.table.table-condensed.small.table-bordered
    %tbody
      %tr
        %th.text-right{:width=>'25%'}= t('attributes.aufnr')
        %td{:width=>'25%'}= @record[:aufnr]
        %th.text-right{:width=>'25%'}= t('attributes.matnr')
        %td{:width=>'25%'}= @record[:matnr]
      %tr
        %th.text-right= t('attributes.dcode')
        %td= @record[:atwrt]
        %th.text-right= t('attributes.charg')
        %td= @record[:charg]
      %tr
        %th.text-right= t('attributes.menge')
        %td
          = @record[:menge]
          = @record[:meins]
        %th.text-right= '入庫 / 訂單'
        %td
          %span.text-primary
            = @record[:wemng]
          \/
          = @record[:psmng]
          = @record[:meins]
      %tr
        %th.text-right= t('attributes.werks')
        %td
          = @record[:werks]
          \/
          = @record[:lgort]
        %th.text-right= t('attributes.mblnr')
        %td= "#{@record[:mjahr]}-#{@record[:mblnr]}"
      %tr
        %th.text-right= t('attributes.budat')
        %td= "#{@record[:budat]} / #{@record[:cputm]}"
        %th.text-right= t('attributes.usnam')
        %td= @record[:usnam]

= form_tag(print_box_label_work_order_path(@record[:rowid]), method: 'post', class: 'form-inline') do
  = hidden_field_tag :mblnr, @record[:mblnr]
  = hidden_field_tag :mjahr, @record[:mjahr]
  = hidden_field_tag :zeile, @record[:zeile]
  %table.table.table-bordered
    %thead
      %tr
        %th.text-right{:width=>'120px'} 項目
        %th.text-right{:width=>'10px'} 每包裝數量
        %th.text-right{:width=>'10px'} 箱/棧板數
        %th.text-right{:width=>'10px'} 總數量
        %th
    %tbody
      %tr
        %td.text-right 紙箱/膠框
        %td= text_field_tag :box_qty, nil, class: 'form-control input-sm small text-right', value: @record[:box_qty]
        %td= text_field_tag :no_of_box1, nil, class: 'form-control input-sm small text-right', value: @record[:no_of_box1]
        %td= text_field_tag :total_qty1, nil, class: 'form-control input-sm small text-right', value: @record[:box_qty] * @record[:no_of_box1]
      %tr
        %td.text-right 尾數箱/尾數框
        %td= text_field_tag :box_qty2, nil, class: 'form-control input-sm small text-right', value: @record[:box_qty2]
        %td= text_field_tag :no_of_box2, nil, class: 'form-control input-sm small text-right', value: @record[:no_of_box2]
        %td= text_field_tag :total_qty2, nil, class: 'form-control input-sm small text-right', value: @record[:box_qty2] * @record[:no_of_box2]
      %tr.bg-warning
        %td.text-right 棧板
        %td= text_field_tag :pallet_qty, nil, class: 'form-control input-sm small text-right', value: @record[:pallet_qty]
        %td= text_field_tag :no_of_pallet1, nil, class: 'form-control input-sm small text-right', value: @record[:no_of_pallet1]
        %td= text_field_tag :total_box1, nil, class: 'form-control input-sm small text-right', value: @record[:pallet_qty] * @record[:no_of_pallet1]
      %tr.bg-warning
        %td.text-right 尾數棧板
        %td= text_field_tag :pallet_qty2, nil, class: 'form-control input-sm small text-right', value: @record[:pallet_qty2]
        %td= text_field_tag :no_of_pallet2, nil, class: 'form-control input-sm small text-right', value: @record[:no_of_pallet2]
        %td= text_field_tag :total_box2, nil, class: 'form-control input-sm small text-right', value: @record[:pallet_qty2] * @record[:no_of_pallet2]

  選擇打印機

  = select_tag 'printer_id', options_from_collection_for_select(Printer.all.select(:uuid,:code), 'uuid', 'code', current_user.printer_id), class: 'select optional form-control'

  = button_tag class: 'btn btn-primary btn-form-submit btn-lg', type: 'button' do
    打印外箱條碼標籤
    %span.glyphicon.glyphicon-print

app/views/work_orders/edit.html.haml
%h3= t('edit_work_order')
%h5
  = link_to t('show'), @work_order
  \|
  = link_to t('back'), work_orders_path

= render 'form'

%h5
  = link_to t('show'), @work_order
  \|
  = link_to t('back'), work_orders_path

app/views/work_orders/index.html.haml
%h3= t('attributes.work_order')

%h5
  = link_to t('new_work_order'), new_work_order_path

= form_tag(work_orders_url, method: 'get', class: 'form-inline') do
  = text_field_tag :name, nil, placeholder: t('attributes.name'), class: 'form-control input-sm', value: params[:name]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search

.table-responsive
  %table.table.table-hover.table-condensed.table-bordered
    %thead
      %tr
        %th= t('action')
    %tbody
      - @work_orders.each do |work_order|
        %tr
          %td
            = link_to t('edit'), edit_work_order_path(work_order)
            |
            = link_to t('delete'), work_order, :method => :delete, :data => { :confirm => t('confirm_delete')}


%h5
  = link_to t('new_work_order'), new_work_order_path

= paginate @work_orders unless @work_orders.empty?

app/views/work_orders/new.html.haml
%h3= t('new_work_order')

%h5
  = link_to t('back'), work_orders_path

= render 'form'

%h5
  = link_to t('back'), work_orders_path

app/views/work_orders/receipt.html.haml
%h3= t('work_order_receipt')

= form_tag(receipt_work_orders_url , method: 'get', class: 'form-inline') do
  = text_field_tag :budat, nil, placeholder: t('attributes.budat'), class: 'form-control input-sm', value: params[:budat] || Time.now.strftime('%Y%m%d')
  = text_field_tag :usnam, nil, placeholder: t('attributes.usnam'), class: 'form-control input-sm', value: params[:usnam]
  = text_field_tag :werks, nil, placeholder: t('attributes.werks'), class: 'form-control input-sm', value: params[:werks]
  = text_field_tag :matnr, nil, placeholder: t('attributes.matnr'), class: 'form-control input-sm', value: params[:matnr]
  = text_field_tag :aufnr, nil, placeholder: t('attributes.aufnr'), class: 'form-control input-sm', value: params[:aufnr]
  = button_tag class: 'btn btn-success btn-form-submit', type: 'button' do
    %span.glyphicon.glyphicon-search

.table-responsived
  %table.table.table-hover.table-condensed.small
    %thead
      %tr
        %th= t('action')
        %th= t('attributes.mblnr')
        %th= t('attributes.cputm')
        %th= t('attributes.aufnr')
        %th= t('attributes.matnr')
        %th= t('attributes.charg')
        %th= t('attributes.dcode')
        %th.text-right= t('attributes.menge')
        %th= t('attributes.usnam')
        %th= t('attributes.werks')
        %th= t('attributes.lgort')
    %tbody
      - @list.each do |row|
        %tr
          %td
            = link_to t('print_receipt'), stock_in_label_work_order_path(row.rowid)
            |
            = link_to t('print_box_label'), confirm_box_label_work_order_path(row.rowid)
          %td= row.mblnr
          %td= row.cputm
          %td= row.aufnr
          %td= row.matnr
          %td= row.charg
          %td= row.atwrt
          %td.text-right= number_with_precision(row.menge, precision: 12, significant: true, strip_insignificant_zeros: true, delimiter: ',')
          %td= row.usnam
          %td= row.werks
          %td= row.lgort

app/views/work_orders/show.html.haml
%h3= t('attributes.work_order')
%h5
  = link_to t('edit'), edit_work_order_path(@work_order)
  \|
  = link_to t('back'), work_orders_path

= render partial: 'layouts/show', :locals => {object: @work_order}

%h5
  = link_to t('edit'), edit_work_order_path(@work_order)
  \|
  = link_to t('back'), work_orders_path