config/routes.rb
Rails.application.routes.draw do

  resources :printers

  resources :barcodes do
    get :scan, on: :collection
    get :unlink_pallet, on: :member
    get :in, on: :collection
    get :in_scan, on: :collection
    post :in_putaway, on: :collection
    get :repeat_printer, on: :collection
    get :printer_label, on: :collection
  end

  resources :stock_masters
  resources :stock_trans do
    get :in, :on => :collection
    get :in_scan, :on => :collection
    get :out, :on => :collection
  end

  resources :work_orders do
    get :receipt, :on => :collection
    get :confirm_box_label, :on => :member
    post :print_box_label, :on => :member
    get :stock_in_label, :on => :member
  end

  root to: 'visitors#index' #首頁

  devise_for :users

  resources :users do
    get :autocomplete_user_email, :on => :collection
  end

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'ISTOCK', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
-if user_signed_in?
  %li=# link_to 'Edit account', edit_user_registration_path
  %li= link_to '工單收貨', receipt_work_orders_path
  %li= link_to '物料主檔', stock_masters_path
  %li.dropdown
    %a.dropdown-toggle{data: {toggle: "dropdown"}, href: "#"}
      = '棧板管理'
      %b.caret
    %ul.dropdown-menu
      %li= link_to '入庫', in_barcodes_path
  %li.dropdown
    %a.dropdown-toggle{data: {toggle: "dropdown"}, href: "#"}
      = '條碼管理'
      %b.caret
    %ul.dropdown-menu
      %li= link_to '查詢及解除棧板', scan_barcodes_path
      %li= link_to '上貨架及轉貨架', in_barcodes_path
      %li= link_to '出庫', out_stock_trans_path

  %li= link_to '打印機', printers_path if current_user.role == 'admin'
  %li= link_to '打印', printer_label_barcodes_path if current_user.role == 'admin'
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
  %li= link_to 'Users', users_path if current_user.role == 'admin'
-else
  %li= link_to 'Sign in', new_user_session_path

app/views/layouts/_show.html.haml
.table-responsive
  %table.table.table-hover.table-condensed.table-bordered
    %tr
      - i = 0
      - object.attributes.each do |attribute|
        - if i == 2
          - i = 1
          %tr
        - else
          - i = i + 1
        %th= t("attributes.#{attribute[0]}")
        - if not attribute[1].nil? and (attribute[0][attribute[0].length - 3 .. attribute[0].length - 1]) == '_id' and not object.class.reflections[attribute[0][0 .. attribute[0].length - 4]].nil?
          - child_object = object.read_attribute_for_serialization(attribute[0][0 .. attribute[0].length - 4])
          %td= link_to child_object.name, child_object
        - else
          %td= attribute[1]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}/
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}/

    %title= "#{controller_name}.#{action_name}"
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'istock'}"}

    %link{href: '/css/bootstrap.min.css', rel:'stylesheet'}
    %link{href: '/css/bootstrap-datetimepicker.min.css', rel:'stylesheet'}
    %link{href: '/css/bootstrap-editable.css', rel:'stylesheet'}
    %script{src: '/js/jquery.min.js'}
    %script{src: '/js/jquery_ujs.js'}
    %script{src: '/js/bootstrap.min.js'}
    %script{src: '/js/moment.min.js'}
    %script{src: '/js/bootstrap-datetimepicker.min.js'}
    %script{src: '/js/bootstrap3-autocomplete-input.min.js'}
    %script{src: '/js/bootstrap3-typeahead.min.js'}
    %script{src: '/js/bootstrap-editable.min.js'}

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'

    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    #wrap
      .container
        .narrow-well
          = render 'layouts/messages'
          .container
            = yield
    #footer
      .container